//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GwCentral.cetApoio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicosQRCodeSoap", Namespace="http://cetaplica/smee/qrcode/")]
    public partial class ServicosQRCode : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listarLocaisOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarLocalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicosQRCode() {
            this.Url = global::GwCentral.Properties.Settings.Default.GwCentral_cetApoio_ServicosQRCode;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listarLocaisCompletedEventHandler listarLocaisCompleted;
        
        /// <remarks/>
        public event listarLocalCompletedEventHandler listarLocalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cetaplica/smee/qrcode/listarLocais", RequestNamespace="http://cetaplica/smee/qrcode/", ResponseNamespace="http://cetaplica/smee/qrcode/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaLocaisResultado listarLocais(int idEmpresa, string chave) {
            object[] results = this.Invoke("listarLocais", new object[] {
                        idEmpresa,
                        chave});
            return ((ListaLocaisResultado)(results[0]));
        }
        
        /// <remarks/>
        public void listarLocaisAsync(int idEmpresa, string chave) {
            this.listarLocaisAsync(idEmpresa, chave, null);
        }
        
        /// <remarks/>
        public void listarLocaisAsync(int idEmpresa, string chave, object userState) {
            if ((this.listarLocaisOperationCompleted == null)) {
                this.listarLocaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarLocaisOperationCompleted);
            }
            this.InvokeAsync("listarLocais", new object[] {
                        idEmpresa,
                        chave}, this.listarLocaisOperationCompleted, userState);
        }
        
        private void OnlistarLocaisOperationCompleted(object arg) {
            if ((this.listarLocaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarLocaisCompleted(this, new listarLocaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cetaplica/smee/qrcode/listarLocal", RequestNamespace="http://cetaplica/smee/qrcode/", ResponseNamespace="http://cetaplica/smee/qrcode/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaLocaisResultado listarLocal(int idEmpresa, string chave, int idLocal) {
            object[] results = this.Invoke("listarLocal", new object[] {
                        idEmpresa,
                        chave,
                        idLocal});
            return ((ListaLocaisResultado)(results[0]));
        }
        
        /// <remarks/>
        public void listarLocalAsync(int idEmpresa, string chave, int idLocal) {
            this.listarLocalAsync(idEmpresa, chave, idLocal, null);
        }
        
        /// <remarks/>
        public void listarLocalAsync(int idEmpresa, string chave, int idLocal, object userState) {
            if ((this.listarLocalOperationCompleted == null)) {
                this.listarLocalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarLocalOperationCompleted);
            }
            this.InvokeAsync("listarLocal", new object[] {
                        idEmpresa,
                        chave,
                        idLocal}, this.listarLocalOperationCompleted, userState);
        }
        
        private void OnlistarLocalOperationCompleted(object arg) {
            if ((this.listarLocalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarLocalCompleted(this, new listarLocalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cetaplica/smee/qrcode/")]
    public partial class ListaLocaisResultado {
        
        private Resultado mensagemField;
        
        private LocalResumido[] locaisField;
        
        /// <remarks/>
        public Resultado Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public LocalResumido[] Locais {
            get {
                return this.locaisField;
            }
            set {
                this.locaisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cetaplica/smee/qrcode/")]
    public partial class Resultado {
        
        private int erroField;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cetaplica/smee/qrcode/")]
    public partial class LocalResumido {
        
        private int idLocalField;
        
        private string descricaoField;
        
        private string distritoField;
        
        private string areaField;
        
        private string departamentoField;
        
        private string centralSemaforosField;
        
        private string prioridadeField;
        
        private System.Nullable<float> latitudeField;
        
        private System.Nullable<float> longitudeField;
        
        private System.Nullable<int> idEmpresaField;
        
        private string linkField;
        
        /// <remarks/>
        public int IdLocal {
            get {
                return this.idLocalField;
            }
            set {
                this.idLocalField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public string CentralSemaforos {
            get {
                return this.centralSemaforosField;
            }
            set {
                this.centralSemaforosField = value;
            }
        }
        
        /// <remarks/>
        public string Prioridade {
            get {
                return this.prioridadeField;
            }
            set {
                this.prioridadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<float> Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                this.idEmpresaField = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void listarLocaisCompletedEventHandler(object sender, listarLocaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarLocaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarLocaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaLocaisResultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaLocaisResultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void listarLocalCompletedEventHandler(object sender, listarLocalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarLocalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarLocalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaLocaisResultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaLocaisResultado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591